### ISSUE TITLE
The data is not JSON due to a typo.

### ISSUE THREAD

**Issue by GlobalGamer2015** [abdipr/myinstants-api#1] opened 2024-12-13 13:47 UTC
Each id is missing a quote.

`{
            "id": akh-26815",
            "title": "AKH",
            "url": "https://www.myinstants.com/en/instant/akh-26815",
            "mp3": "https://www.myinstants.com/media/sounds/akh.mp3"
        },
        {
            "id": vine-boom-sound-70972",
            "title": "VINE BOOM SOUND",
            "url": "https://www.myinstants.com/en/instant/vine-boom-sound-70972",
            "mp3": "https://www.myinstants.com/media/sounds/vine-boom.mp3"
        },
        {
            "id": fart",
            "title": "Fart",
            "url": "https://www.myinstants.com/en/instant/fart",
            "mp3": "https://www.myinstants.com/media/sounds/dry-fart.mp3"
        },
        {
            "id": anime-wow",
            "title": "Anime Wow",
            "url": "https://www.myinstants.com/en/instant/anime-wow",
            "mp3": "https://www.myinstants.com/media/sounds/anime-wow-sound-effect.mp3"
        },`

**Comment by abdipr** [comment] 2024-12-14 09:12
Thank you for submitting this issue, the problem is now fixed!

**Closed as completed by abdipr** 2024-12-14 09:12 UTC
